Repository dealii/publication-list, pull requests merged in 2018-11, with the labels that each got.

#1 Initial publication list
  .gitignore
  publications-1998.bib
  publications-1999.bib
  publications-2000.bib
  publications-2001.bib
  publications-2002.bib
  publications-2003.bib
  publications-2004.bib
  publications-2005.bib
  publications-2006.bib
  publications-2007.bib
  publications-2008.bib
  publications-2009.bib
  publications-2010.bib
  publications-2011.bib
  publications-2012.bib
  publications-2013.bib
  publications-2014.bib
  publications-2015.bib
  publications-2016.bib
  publications-2017.bib
  publications-2018.bib
Labels: new entry

#2 Add new entries accumulated offline
  publications-2016.bib
  publications-2017.bib
  publications-2018.bib
Labels: do not merge yet, new entry

#7 Clean up original entries
  offline/publication_list.tex
  publications-1998.bib
  publications-1999.bib
  publications-2001.bib
  publications-2002.bib
  publications-2003.bib
  publications-2004.bib
  publications-2005.bib
  publications-2006.bib
  publications-2007.bib
  publications-2008.bib
  publications-2009.bib
  publications-2010.bib
  publications-2011.bib
  publications-2012.bib
  publications-2013.bib
  publications-2014.bib
  publications-2015.bib
  publications-2016.bib
  publications-2017.bib
  publications-2018.bib
Labels: maintenance

#12 Fix entry that bibtex sees as a runaway command
  publications-2017.bib
Labels: fix entry

#5 add automated testing with Jenkins
  Jenkinsfile
Labels: ready to test

#14 new entries
  publications-2016.bib
  publications-2018.bib
Labels: new entry, ready to test

#18 Update bibliography entries: 2001
  publications-2001.bib
Labels: ready to test, update entry

#17 Update bibliography entries: 2000
  publications-2000.bib
Labels: ready to test, update entry

#16 Update bibliography entries: 1999
  publications-1999.bib
Labels: ready to test, update entry

#15 Update bibliography entries: 1998
  publications-1998.bib
Labels: ready to test, update entry

#20 Add new entries (and fix some existing ones) using Timo's curated list
  publications-2016.bib
  publications-2017.bib
  publications-2018.bib
  publications-2019.bib
Labels: new entry, ready to test, update entry

#21 Update all entries with author "Pelteret"
  publications-2012.bib
  publications-2013.bib
  publications-2014.bib
  publications-2015.bib
  publications-2016.bib
  publications-2017.bib
  publications-2018.bib
Labels: ready to test, update entry

#22 Jenkins: also test master
  Jenkinsfile
Labels: ready to test

#23 add: phd theses
  publications-2017.bib
  publications-2018.bib
Labels: ready to test

#29 remove owner and timestamp
  publications-1998.bib
  publications-1999.bib
  publications-2000.bib
  publications-2001.bib
  publications-2016.bib
  publications-2017.bib
  publications-2018.bib
  publications-2019.bib
Labels: ready to test

#30 Readme: build status and links
  README.md
Labels: ready to test

#27 Also print the year in all entries.
  jabref-template/listrefs.layout
Labels: ready to test

#37 jenkins: check for non-ascii chars
  Jenkinsfile
Labels: ready to test

#34 Fix a few 2018 entries.
  publications-2018.bib
Labels: ready to test

#38 Fix spelling of 'Texas A&M'.
  publications-2005.bib
  publications-2009.bib
  publications-2010.bib
  publications-2011.bib
  publications-2012.bib
  publications-2013.bib
  publications-2014.bib
  publications-2015.bib
  publications-2016.bib
  publications-2017.bib
Labels: ready to test

#36 Add a template file for PhD theses.
  jabref-template/listrefs.phdthesis.layout
Labels: ready to test

#39 Add notes for entries that are "not yet published"
  publications-2008.bib
  publications-2011.bib
  publications-2012.bib
  publications-2013.bib
  publications-2015.bib
  publications-2016.bib
  publications-2017.bib
  publications-2018.bib
Labels: fix entry, ready to test

#41 Print 'note' fields.
  jabref-template/listrefs.layout
Labels: ready to test

#44 Also update the README file about theses.
  README.md
Labels: ready to test

#45 Fix a few thesis entries.
  publications-2012.bib
  publications-2013.bib
  publications-2017.bib
Labels: ready to test

#46 pdf: make links clickable
  offline/publication_list.tex
Labels: ready to test
