Repository dealii/publication-list, pull requests merged in 2019-01, with the labels that each got.

#54 fix urls
  publications-2015.bib
  publications-2017.bib
  publications-2018.bib
Labels: fix entry, ready to test

#55 new entries
  publications-2018.bib
Labels: new entry, ready to test

#56 Add one.
  publications-2018.bib
Labels: ready to test
