Repository dealii/publication-list, pull requests merged in 2020-06, with the labels that each got.

#202 Add one.
  publications-2020.bib
Labels: ready to test

#203 some new publications in 2020
  publications-2020.bib
Labels: ready to test

#204 List 9.2 on the publications page.
  publications.include
Labels: ready to test

#205 Add two PhD theses.
  publications-2020.bib
Labels: ready to test

#206 Update references
  publications-2019.bib
  publications-2020.bib
Labels: ready to test, update entry

#207 Add entry Comellas2020
  publications-2020.bib
Labels: ready to test

#208 Add missing author names in Comellas2020
  publications-2020.bib
Labels: fix entry, ready to test

#209 Add one.
  publications-2020.bib
Labels: ready to test

#210 Use less vertical space for the 9.2 entry.
  publications.include
Labels: ready to test
