Repository dealii/publication-list, pull requests merged in 2023-09, with the labels that each got.

#535 Added 6. Updated 2.
  publications-2022.bib
  publications-2023.bib
Labels: ready to test

#538 Miscellaneous updates.
  publications-2011.bib
  publications-2014.bib
  publications-2015.bib
  publications-2017.bib
Labels: new entry, ready to test, fix entry

#537 Articles that mention, but do not use deal.II.
  publications-2014.bib
  publications-2015.bib
  publications-2016.bib
  publications-2017.bib
  publications-2018.bib
Labels: maintenance, ready to test

#536 Update arxiv publications 2009 - 2017.
  publications-2009.bib
  publications-2010.bib
  publications-2012.bib
  publications-2014.bib
  publications-2015.bib
  publications-2016.bib
  publications-2017.bib
  publications-2018.bib
  publications-2019.bib
  publications-2021.bib
Labels: ready to test, update entry

#540 Paper for 9.5 release is published.
  publications-2023.bib
  publications.include
Labels: ready to test

#542 Augment an entry.
  publications-2022.bib
Labels: ready to test

#544 Update articles of Mohebujjaman.
  publications-2015.bib
  publications-2016.bib
  publications-2017.bib
  publications-2018.bib
  publications-2022.bib
Labels: ready to test

#545 Update parallel hp paper.
  publications-2022.bib
  publications-2023.bib
  publications.include
Labels: ready to test

#546 Fix an entry.
  publications-2014.bib
Labels: ready to test
